# 配置文件

questions:
  - id: 1
    q: "此曲只应天上有"
    a: ["c", "q", "zh", "y", "t", "sh", "y"]
  
  - id: 2
    q: "旧时王谢堂前燕"
    a: ["j", "sh", "w", "x", "t", "q", "y"]
  
  - id: 3
    q: "早有蜻蜓立上头"
    a: ["z", "y", "q", "t", "l", "sh", "t"]
  
  - id: 4
    q: "山外青山楼外楼"
    a: ["sh", "w", "q", "sh", "l", "w", "l"]
  
  - id: 5
    q: "春潮带雨晚来急"
    a: ["ch", "ch", "d", "y", "w", "l", "j"]
  
  - id: 6
    q: "在地愿为连理枝"
    a: ["z", "d", "y", "w", "l", "l", "zh"]
  
  - id: 7
    q: "葡萄美酒夜光杯"
    a: ["p", "t", "m", "j", "y", "g", "b"]
  
  - id: 8
    q: "雄鸡一唱天下白"
    a: ["x", "j", "y", "ch", "t", "x", "b"]
  
  - id: 9
    q: "却话巴山夜雨时"
    a: ["q", "h", "b", "sh", "y", "y", "sh"]
  
  - id: 10
    q: "朝辞白帝彩云间"
    a: ["ch", "c", "b", "d", "c", "y", "j"]
  
  - id: 11
    q: "留取丹心照汗青"
    a: ["l", "q", "d", "x", "zh", "h", "q"]
  
  - id: 12
    q: "千树万树梨花开"
    a: ["q", "sh", "w", "sh", "l", "h", "k"]
  
  - id: 13
    q: "春风得意马蹄疾"
    a: ["ch", "f", "d", "y", "m", "t", "j"]
  
  - id: 14
    q: "乱花渐欲迷人眼"
    a: ["l", "h", "j", "y", "m", "r", "y"]
  
  - id: 15
    q: "水面初平云脚低"
    a: ["sh", "m", "ch", "p", "y", "j", "d"]
  
  - id: 16
    q: "映日荷花别样红"
    a: ["y", "r", "h", "h", "b", "y", "h"]
  
  - id: 17
    q: "疑是银河落九天"
    a: ["y", "sh", "y", "h", "l", "j", "t"]
  
  - id: 18
    q: "不拘一格降人才"
    a: ["b", "j", "y", "g", "j", "r", "c"]
  
  - id: 19
    q: "孤帆远影碧空尽"
    a: ["g", "f", "y", "y", "b", "k", "j"]
  
  - id: 20
    q: "除却巫山不是云"
    a: ["ch", "q", "w", "sh", "b", "sh", "y"]
  
  - id: 21
    q: "万紫千红总是春"
    a: ["w", "z", "q", "h", "z", "sh", "ch"]
  
  - id: 22
    q: "满城尽带黄金甲"
    a: ["m", "ch", "j", "d", "h", "j", "j"]
  
  - id: 23
    q: "化作春泥更护花"
    a: ["h", "z", "ch", "n", "g", "h", "h"]
  
  - id: 24
    q: "只留清气满乾坤"
    a: ["zh", "l", "q", "q", "m", "q", "k"]
  
  - id: 25
    q: "江山代有才人出"
    a: ["j", "sh", "d", "y", "c", "r", "ch"]
  
  - id: 26
    q: "两个黄鹂鸣翠柳"
    a: ["l", "g", "h", "l", "m", "c", "l"]
  
  - id: 27
    q: "蓝田日暖玉生烟"
    a: ["l", "t", "r", "n", "y", "sh", "y"]
  
  - id: 28
    q: "要留清白在人间"
    a: ["y", "l", "q", "b", "z", "r", "j"]
  
  - id: 29
    q: "总把新桃换旧符"
    a: ["z", "b", "x", "t", "h", "j", "f"]
  
  - id: 30
    q: "天若有情天亦老"
    a: ["t", "r", "y", "q", "t", "y", "l"]
  
  - id: 31
    q: "天生我材必有用"
    a: ["t", "sh", "w", "c", "b", "y", "y"]
  
  - id: 32
    q: "淡妆浓抹总相宜"
    a: ["d", "zh", "n", "m", "z", "x", "y"]
  
  - id: 33
    q: "海上明月共潮生"
    a: ["h", "sh", "m", "y", "g", "ch", "sh"]
  
  - id: 34
    q: "直挂云帆济沧海"
    a: ["zh", "g", "y", "f", "j", "c", "h"]
  
  - id: 35
    q: "小荷才露尖尖角"
    a: ["x", "h", "c", "l", "j", "j", "j"]
  
  - id: 36
    q: "直把杭州作汴州"
    a: ["zh", "b", "h", "zh", "z", "b", "zh"]
  
  - id: 37
    q: "春江水暖鸭先知"
    a: ["ch", "j", "sh", "n", "y", "x", "zh"]
  
  - id: 38
    q: "一片冰心在玉壶"
    a: ["y", "p", "b", "x", "z", "y", "h"]
  
  - id: 39
    q: "只缘身在此山中"
    a: ["zh", "y", "sh", "z", "c", "sh", "zh"]
  
  - id: 40
    q: "道是无晴却有晴"
    a: ["d", "sh", "w", "q", "q", "y", "q"]
